---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://grafana.github.io/helm-charts
      chart: grafana
      version: 6.43.4
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 5m
  values:
    grafana.ini:
      server:
        root_url: 'https://grafana.${SECRET_DOMAIN}'
    adminPassword: '${SECRET_GRAFANA_PASSWORD}'

    dashboards:
      default:
        speedtest:
          gnetId: 13665
          revision: 1
          datasource: Prometheus
        # Ref: https://grafana.com/grafana/dashboards/7845
        zfs:
          gnetId: 7845
          revision: 4
          datasource: Prometheus
        longhorn:
          datasource: Prometheus
          gnetId: 13032
          revision: 6
    sidecar:
      datasources:
        enabled: true
        searchNamespace: ALL
        # defaultDatasourceEnabled: false
      dashboards:
        enabled: true
        searchNamespace: ALL
    datasources:
      datasources.yaml:
        apiVersion: 1
        # list of datasources that should be deleted from the database
        deleteDatasources:
          - name: Loki
            orgId: 1
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://thanos-query:9090/
            isDefault: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: 'letsencrypt-production'
      hosts:
        - 'grafana.${SECRET_DOMAIN}'
      tls:
        - hosts:
            - 'grafana.${SECRET_DOMAIN}'
          secretName: 'grafana-tls'

    serviceAccount:
      create: true
      autoMount: true
    persistence:
      enabled: false
