---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt
  namespace: home
spec:
  # FIXME Upgrade failed
  suspend: true
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: docker.io/koenkk/zigbee2mqtt
      tag: 1.28.2

    config:
      mqtt:
        base_topic: zigbee2mqtt
        server: "mqtt://mosquitto.home"
        user: '${SECRET_MQTT_USERNAME}'
        password: '${SECRET_MQTT_PASSWORD}'

      homeassistant: true

      device_options:
        retain: true

      permit_join: false

      serial:
        port: 'tcp://192.168.42.111:6638'

      advanced:
        log_output:
          - console
        network_key:
          - 204
          - 61
          - 75
          - 23
          - 44
          - 230
          - 24
          - 203
          - 53
          - 5
          - 248
          - 32
          - 50
          - 84
          - 44
          - 159
        pan_id: 6752

      # Both of these need to be enabled for the webui
      frontend:
        port: 8080

    env:
      ZIGBEE2MQTT_DATA: /data

    service:
      main:
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
        hosts:
          - host: &host "zigbee2mqtt.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
            secretName: 'zigbee2mqtt-tls'

    persistence:
      data:
        enabled: true
        mountPath: "/data"
        existingClaim: zigbee2mqtt-data

    resources:
      requests:
        cpu: 15m
        memory: 127M
      limits:
        memory: 1364M
