apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt
    namespace: home
stringData:
    mqtt_user: ENC[AES256_GCM,data:UtPnCRJq/g==,iv:WfZlqIdGXQ0HWdI80aGLqD/sV10LkOfeSUfpctTeZ5o=,tag:JwC4EycKwp7vJsIVgyTCMQ==,type:str]
    mqtt_password: ENC[AES256_GCM,data:O9GPLrwAail5txxnulpDjalLiprb6Xy9,iv:0jkcHl6rR/Gwnkr99vLP8JvFjWW7fZ+WsvWrJL4xask=,tag:uJIMKK8cNuo67IAJqbeGVQ==,type:str]
    zigbee_adapter_port: ENC[AES256_GCM,data:UNKLUzGzlf7CYDFOVDyttrwznBGvFp1n4g==,iv:pkgYFvN9cwKE0KpkkCSbGb1wyXVhrPgzBNZmXSwIUMQ=,tag:OTYxXS2gS839JVZ50CNd9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhVkVoUUxPSFgvRXlkZmRi
            TkhoVUc1SXE3Qm5WSXBFNTZkdFh3Z2VXQ0JvCmloOW1ldzFCSUpTS1pHOGpKWTVF
            ZGtoeDd5RDBMUTRQTnU2YmFnTVladDQKLS0tICtEWXFsbmJkQ0xwaTQ4am85eFo4
            ZnZrM050a0paaVEwb01XZWVJMytDVzAKjumK0yAOKobpYfqb9eveSSLeLntIeW9C
            XzCjz2LK8kdRqcEQJpuYWULWsqmrnruTRJN1zrPnad6lTq+ya7VxOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-22T21:42:53Z"
    mac: ENC[AES256_GCM,data:LtgVrB0Fzg23lhMMXDfTQh8MeABxBIsklWbsr7p+3JKtoWMLFeY+WW8gtqfcLO3Yzi791O3+Rx3GoUwTfWMFcAC9h7KHs2gSmA5bqGOtFPXgoatKTTP3RBVX6T3Ogbn+wMXU3eQjCP0ELlmdJ3dhGTfQdIFyj+XsKUd6wyDiClQ=,iv:xjxtkxN3JKS/XzBmStAfwYZvVxVVdG26z6SgLiRsgKA=,tag:c4HLwJCFrvkolPNaMN6nTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
