---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jupyterhub
  namespace: dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: jupyterhub-secret
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: JUPYTER_CLIENT_ID
