# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: home-assistant
    namespace: home
stringData:
    HASS_ELEVATION: ENC[AES256_GCM,data:GEe4,iv:jOAZEWeoa2s61fLWZZmK0o+h3JotCuEE9ojduyGXU74=,tag:JdsaTf+txzIxeXjjqgtZiQ==,type:int]
    HASS_LATITUDE: ENC[AES256_GCM,data:7xxpagasTvA=,iv:/KMPbjvYHFjRDJh4qpYDHQI+lVirJJRq83LFp86pD2I=,tag:VrW9aHXq/RRsjQiuR0Ii6g==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:ua83+KmjBWxjAQ==,iv:nDP/38yC50ATlb1xzTmUSC7k51NWTanH4EPOk8lv6Zs=,tag:Y46j3zgYaAMtYHCIlFqoBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxMWJURTBhZ2l5QnZiaGZK
            L2N3ZUdyKzViNUpNRE8wbCtoUW5Ocjl0VzFrCnpPbWxrcWRFZGRxYVBXcWk1a0oz
            UVZqWHI0dVYwUUJoaGVLNDY5ZGVta0UKLS0tIHRkalE3S3NudVUwek9oOGg1MHFM
            cG5Kd3kzUmJPL2tYR3JSbGJZTmYvUG8K0/UsoisPe6iF2k7st4sTuABH06mYzPKk
            rfDqNBa1lf9Bb6j8KVnwFJ8W8sZs7OqWV8nL7iM9WzL8A2WMp1MX0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-01T16:55:04Z"
    mac: ENC[AES256_GCM,data:AX1l478PijsT9rKphRPrvt03/Yjrz0x/eqoA5Ak+dHW4y6VcZDGLY0j0XY2yrdWg2K33dxwRZ2915TPO+vMLLUgppLjVJXR8RWNNj+CwitHx0dlLToPqZCyXKV5mO9Xrte7e87f78UeckL+h9wNK6GcS8gxpGnXihCme6UP5OXY=,iv:tbXvYXM4DMfAp0HDJLrc2YTi9mh8LqbtR1Z8y/Tg81Y=,tag:uvuO1oXGkW2X9rZPo5uVCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
