---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: mosquitto-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: MOSQUITTO_USERNAME
    - secretKey: password
      remoteRef:
        key: MOSQUITTO_PASSWORD
    - secretKey: mosquitto_pwd
      remoteRef:
        key: MOSQUITTO_PWD
