# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:KhEKWo1P5w==,iv:pFKZOSoyN19fOfrf22bNfPglfdB5Mhw5CJjzVgEsy1Y=,tag:NbyYQ5DS4xS8U874u14lCA==,type:str]
    password: ENC[AES256_GCM,data:MNSskZQMqbbPAEPCtIPakao3P8+mq3FI,iv:zsoshj6NXDS3Qkkmv7TLGsc/LRZxAd/5hmDb8y+CPHY=,tag:JtGK059F44oyoG9JfAyUJQ==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:4GuB/goT/67DwtxEIWfCuf0HLU67TM8e96cDaK/fZDw=,iv:IoZXj60YGjz3tbwgYChloU6fY0GOq8+KOvbiQGfU9to=,tag:6TFgU1KyE3pS81jvGCeFUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbmk3aDg0MlU4Y3FtajRs
            TFFHMzJza05lQjgrTGFXMlREYjhuTnprbGg0CjlEZVZib3kzdit2MWNGVzd4S29v
            YmZlMTI5c2p2WmE1MkxDbnBnS2VOclkKLS0tIGZSZWJ2SCtiRG1qd3JvNk1aTGhh
            dkVFR2d6akV3cUZYNVJ1OVNEbUppalkKLnS12yvGmtIAFqzW5hVZG2Tnxwaqj0vm
            49CUb2Q1ExtA0k5BRkF+3un2LRoLFRdao1TJmiMWacuVYtqpgX3RiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-20T20:47:17Z"
    mac: ENC[AES256_GCM,data:VoFw1RjiM7q4RUgnsEbWb50FE9r5M0EjK7ZdYmTWKu3f/jcV0ZEeyqls0tFgY6SplJc10Kx8O4Be7HDdmA5v45eGOVoZAFoMykVowplhzVgU48Dcw85YiQJzcseKYSsyiEO+z4Cu/gO7XccnsAOiCs+xNXdSmPjb01DqLleo/PE=,iv:lnA9ElWeLCQud8Cn+2bZTnY0MZEJGBr4vP/1RV9/tAA=,tag:xagMLgEiy3kzfZx7xqdazA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
