---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./audiobookshelf/ks.yaml
  - ./calibre/ks.yaml
  - ./calibre-web/ks.yaml
  - ./immich/ks.yaml
  - ./jellyfin/ks.yaml
  - ./miniflux/ks.yaml
  - ./wizarr/ks.yaml
