apiVersion: v1
kind: Secret
metadata:
    name: ext-postgres-operator-secret
    namespace: operators
type: Opaque
stringData:
    POSTGRES_HOST: ENC[AES256_GCM,data:sc4+0G1SjSqVYNzSXKpiOSPjyVeuIDkFz27AjY6PhMn8NuK7,iv:GSDXzoC5ZZRw4noMzC6FIOhcQ0cwMFwZa4Y5NLcH0q4=,tag:5lTiulOk4vGEDrrc5BJ0Xw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Xucl0ne02RH+FMSoDQ==,iv:EsxMN7dBIqyCPtJQIpoISrSsgUGt31DAJlInNLm7+Ks=,tag:fHOYTcTPz8zl/7Ud8ZrYFQ==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:xpA0Q5dQ9Zsk0jCLVRKBPssL02XUVtlLOMCuuvU=,iv:B5IjanxzMzAZ1TeJYnzZaq3CifbI5IkwgrcXHrUId88=,tag:IvwJ1tMVBZ+dcnHDJCykBw==,type:str]
    POSTGRES_DEFAULT_DATABASE: ENC[AES256_GCM,data:Ce5W1NI/veg=,iv:2w6d9oDTaogguaDGJUwL9rAj4h6U7vTTal4Jl0ooThM=,tag:A8Hfb1SlWKFmQaq19mgzCA==,type:str]
    POSTGRES_URI_ARGS: ""
    POSTGRES_CLOUD_PROVIDER: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPYkNqdEpDRWU0bEg4ZEZS
            dXRqcURQQmNqV1d4cU9YYVlMdFR2Q0VvQjNjCnQvYXlYY3o2aUt5R1pnemRRTkN4
            dXozQ1NibmIwL3NEKzRpTVptMndvbGcKLS0tIDVVNjF6Zit2SXd1NitkL0ZDOFNZ
            bTQ1bzI3c3JCWFJFdVByZkJKd3ZnMzAKq//bEXnLmYN0BGDEMOkEa440U6RgbSjZ
            bbBvKK9dLfrctychZz/x+0ypgw/18PJ5m5ofejF40YJSrNul7DV5sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-11T00:46:03Z"
    mac: ENC[AES256_GCM,data:5xvKaIPIz4h7g90XqCBrcGl9avQ1TLatcdw3n+eBT4ASrobdBTVG6sXzoWyh1cbDw7PbmHPnhozIHa59qRcxnlaNyPuY9c/xTgzvLrWuzBYZ8ReCZwMeHZd61Ia7ZCoTJdUVIBUTQBQ+sAIY1qxd32EtzSv5Q/PddrRN1LgqSwE=,iv:PcO9ATAIqrcxR/VMi+hoTIZsM14dHvPnSFl4+f5Baes=,tag:zMfiMmr6GOOzs4l+2xeBmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
