---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitea
  namespace: dev
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://dl.gitea.io/charts/
      chart: gitea
      version: 7.0.2
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: flux-system
      interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: 'letsencrypt-production'
      hosts:
        - host: 'git.${SECRET_DOMAIN}'
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - 'git.${SECRET_DOMAIN}'
          secretName: 'gitea-tls'

    gitea:
      admin:
        username: '${SECRET_GITEA_USERNAME}'
        password: '${SECRET_GITEA_PASSWORD}'
        email: '${SECRET_GITEA_EMAIL}'
