---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-config-v2
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
