---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: mosquitto
      version: 4.8.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/eclipse-mosquitto
      tag: v2.0.15

    env:
      TZ: '${TIMEZONE}'

    service:
      main:
        type: LoadBalancer
        annotations:
          coredns.io/hostname: 'mqtt.${SECRET_DOMAIN}'
        externalIPs:
          - '${SVC_MOSQUITTO_ADDR}'
        externalTrafficPolicy: Local
    auth:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: mosquitto-config
    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-config-v2
      configinc:
        enabled: true
        type: custom
        volumeSpec:
          secret:
            secretName: mosquitto-config
