# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:VL2F8uU2IQ==,iv:dr4Jr46bqO6l+0M/2TBJwyoc5EhSrNFB1bAIc8TsYe0=,tag:lSoDx6en2MtlTGBjRTDbWQ==,type:str]
    password: ENC[AES256_GCM,data:QsKovbJcF87N2jPoMEImOpG86vHAN6C3VA==,iv:V67MGCKztikjo3BJ6/y7Xz/KxSADUwcrtmyuNfM39+M=,tag:cgF2+L8u0hvm8Zsy9x/gmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMWRIZ0F0K1ZXODhRMTVM
            ak5mSmduTHlxdVNKUFE1UUc5NnBIeENrUlFvClVrSVRBdFB6WFhPZ3BZQ2JSZVJn
            UDJOYUVSeWxLUXMxYnAxZ3Q4dFFIcmMKLS0tIDZFaWh5UC9kbHlDUW5GU3lOVldt
            elB5NU4yL1JIN29HcHhCaUYvMjZZbEUKbkU0t75dWYFAFvKpej8NJDt4c1icgcWb
            rnPolJOmIBrDKGubiXbUt6PexuSUanj/x1K/2nDvrHk0xxtnEC+9Bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T02:06:25Z"
    mac: ENC[AES256_GCM,data:k8aJzuENGzdaAHuwwk8u+LONhzsUr6uafs0fqVkau54C0wGVTBRTbRjdZB5qCuu4gwaU58K4U9p5gO5s62joeM9e7d9QfpqAmUvBpd2WJxYuyGX6ZntyJ8kFg5jqnzS8xOIUgfIPBh5SOe8oC1RHc8SFz1Zc2/BU7Oictf1DS40=,iv:+Qr3HZwQIpWvSBy2bHfeKhwo47fzCvtHYCPpr+n1f/o=,tag:HsqOq1YTPuHZW73Hm8kqKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
