apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:aYJlZ4bcX2jHCZz4SfMYzE0x2EHfr1ZWTDT+GPwhMYa7tXhEirct1Q==,iv:3anxRufYdmPxEq69EzCt0uwQUdI8heaAN1CB2kByIKU=,tag:GaDY2pBKyk5vFzQrBgcrCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ZExrTHFDNTcwc1Q4KzNE
            WHdWYlRKbk9Ld1RLMzNXZkI4bjA2bFN1cTM4Cm5PZVhhS3dPeU9OM3JNSStCcjV2
            bUc0NjNyNFk3NFQwYlg1K1lJVkROdUEKLS0tIDlZa3k1QXZpQ0o1Q2gydjFRd3k5
            N3pSeTczNWRteVdoK0ttWm9DdGpqSEkKjR3YJQc5VhmbaVY5qQEPpPfHZwsNB/DS
            O2mnzviKVmR9h7/bebIMMlU/tFHqLpdJDDp1Y+3JDF6nRKJtGHA4JQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-18T02:59:28Z"
    mac: ENC[AES256_GCM,data:OeZtbWtqSLLeyL3lRsC7hmv3vrqS+45YhX4wFZt2bp0c9MiqNutnWqwrNskU10rzoUsfMeLD1GKhXmo+JRu8dts2HNYahrQkrjiudA7zbvOabQ06TshsPHbgxlUzuE/KG56NZvbYOjKGGrMZGBBoPKnDvge56SrSM+uryTJ+U88=,iv:SqpQ/uruxupOwl64+Peaen0dXdA86IUedBnC+jKNk+k=,tag:n1iy10hsMbjpk9XGG87lRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
