---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.1.20
        k8s-1:
          ansible_host: 192.168.1.23
        k8s-2:
          ansible_host: 192.168.1.24

router:
  hosts:
    opnsense:
      ansible_host: 192.168.1.1
      ansible_shell_executable: /bin/sh
