---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 192.168.1.20
          rook_block_device: /dev/disk/by-id/nvme-PCIe_SSD_22012510000266
        k8s-1:
          ansible_host: 192.168.1.23
          rook_block_device: /dev/disk/by-id/nvme-PCIe_SSD_21050610241091
        k8s-2:
          ansible_host: 192.168.1.24
          rook_block_device: /dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S64ANS0W114130F
    worker:
      hosts:
        k8s-3:
          ansible_host: 192.168.1.25
          rook_block_device: /dev/disk/by-id/nvme-Samsung_SSD_970_EVO_Plus_1TB_S59ANM0W302035F

router:
  hosts:
    opnsense:
      ansible_host: 192.168.1.1
      ansible_shell_executable: /bin/sh
