# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: sonarr-secret
    namespace: downloads
stringData:
    SONARR__API_KEY: ENC[AES256_GCM,data:mJXmouZVpnrS/hypr9HvE3xL6sSJM/4+cNbcc6VEFcY=,iv:tyZrn3sGlLVUk5Ie7rpD4Cr61meyoJlFIdwfZVEPfZk=,tag:knlqhDguk12+xYrRalKAhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMVZaeWFtd0hncURMTDFC
            U2hmeVZpRVo0NDYwSlE2ZkRWUTlpZ0cyRDNRCngvRG1nSTJQaHNWWlhPaEw5dnR5
            d3BtcUpOTGhtTGFaWUdnMGVIaUJRV2MKLS0tIEJSMGVqTFVJdE5SdTg1TmtZUThX
            Z0NuWUg1eXVLbTJCYmxyclJQS3VXQlUKpuyKGSVVwtrQy9ycTq5t3Y90OyPPey5M
            mVV0S0bSLiszSNlSYgVmF8UwWOdhzomHnvYRE7RD/dmdc8BfTWqWUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T01:54:12Z"
    mac: ENC[AES256_GCM,data:nQT+PYhUxNyElhsuSVUCjBUa1SWsTMUmU4i1I0UCRMMVhBM8BsomCizRlQrKqLoemYF9+LMSZqHfMcUO/b2S0qNXJB/KWSNZ2Z8fxKWRaNvhBjmGGT46/76+gnzhekK0ky22vk8YmqadqaNeYQn44DDo27ajJmOo8RbBN9d24N4=,iv:TMzaE7Soaw/Qt5zPILcfdPUg+fwmcWyilrhvKCkR0/U=,tag:jrE1F9+QLdutclpW9R8Skg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
