---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtubedl-material-config-v2
  namespace: downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
