---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/linuxserver/calibre
      tag: version-v5.21.0

    env:
      TZ: '${TIMEZONE}'
      PUID: 568
      PGID: 568

    hostname: calibre

    persistence:
      config:
        enabled: true
        existingClaim: calibre-config-v2
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.101
            path: /srv/nfs
        mountPath: /media

    service:
      webserver:
        enabled: true
        # type: ExternalName
        # externalName: calibre.media.svc.cluster.local

    ingress:
      main:
        enabled: true
        ingressClassName: 'nginx'
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
        hosts:
          - host: 'calibre.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'calibre.${SECRET_DOMAIN}'
            secretName: 'calibre-tls'

    podSecurityContext:
      fsGroup: 0
      supplementalGroups:
        - 100

    resources:
      requests:
        cpu: 0.003
        memory: 768Mi
      limits:
        memory: 1Gi
