---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
  namespace: default
  labels:
      cnpg.io/reload: "true"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: cloudnative-pg-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: POSTGRES_SUPER_USER
    - secretKey: password
      remoteRef:
        key: POSTGRES_SUPER_PASS
    - secretKey: aws-access-key-id
      remoteRef:
        key: CNPG_AWS_ACCESS_KEY_ID
    - secretKey: aws-secret-access-key
      remoteRef:
        key: CNPG_AWS_SECRET_ACCESS_KEY
