---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: cert-manager-secret
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: CLOUDFLARE_APIKEY
