---
apiVersion: db.movetokube.com/v1alpha1
kind: Postgres
metadata:
  name: immich-db
  namespace: media
spec:
  database: immich
---
apiVersion: db.movetokube.com/v1alpha1
kind: PostgresUser
metadata:
  name: immich-user
  namespace: media
spec:
  role: immich
  database: immich-db
  secretName: database
  privileges: OWNER
