---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: immich-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        DB_DATABASE_NAME: &dbname immich
        DB_HOSTNAME: &dbhost postgres-rw.default.svc.cluster.local
        DB_PASSWORD: "{{ .DB_PASSWORD }}"
        DB_USERNAME: "{{ .DB_USERNAME }}"
        TYPESENSE_API_KEY: "{{ .TYPESENSE_API_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: "{{ .DB_USERNAME }}"
        INIT_POSTGRES_PASS: "{{ .DB_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: POSTGRES_SUPER_PASS
    - secretKey: TYPESENSE_API_KEY
      remoteRef:
        key: IMMICH__TYPESENSE_API_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: IMMICH__DB_PASSWORD
