apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: media
type: Opaque
stringData:
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:rcIP,iv:dLUJkpt1Fu3ZVWnjA5ruOnMj8zxMhWKwUU9ax58mM5k=,tag:znhQ+kFHEG41nV90LrNM3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzMGQ1UFoxUVFvSTBYQ25D
            TVBmT2NCTUhCeUw0Ylh1aG1jOUtxZ1ppOFRFCmRVN2lsaG1qWkFGS0RkM2ZYdlJX
            UFMvNUYwbkZOaEN4Um5ZZFV0YVF2SlUKLS0tIGhJZEJnK3BRSS81NjBHSlN0VVR2
            cW1TYnBtWk4wNjM2Q2d4K2E5d2g2d0UKRp+p343y3yZK8gRTR+LFVoGgclGjmGmZ
            H6cXF83bcvdWn4y8S/NSrTFUvFyhiKD6siRbvn2fCP262SLGBJdhhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-10T20:58:15Z"
    mac: ENC[AES256_GCM,data:PiaZ010CdINUIWrZ2NZDmpzzHyup0N4MjEfEvJ8VbB4TXlLMU35ThuTsYzZrVZORAGD8E3ensupV90DDixT+iU41Tt7pb5WcxgEs3C3eEdnmAaaYgUxeOsMmZoj+c/F/3rvQkBeNuZI9vuVUMfgqbIECXCV2YtLAKDOK7KErE+8=,iv:SEkFbtS+5PM9ZD/gmmwpQvcJOpLXg/DE4fkdCcA5kC4=,tag:A4b0Xw8a57I33WpjDWE48g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
