---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: external-dns-cloudflare-secret
    creationPolicy: Owner
  data:
    - secretKey: email
      remoteRef:
        key: CLOUDFLARE_EMAIL
    - secretKey: api-key
      remoteRef:
        key: CLOUDFLARE_APIKEY
