---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-nfs
spec:
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  storageClassName: minio-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # FIXME
    server: 192.168.1.101
    path: /srv/nfs/minio
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-nfs
  namespace: dev
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: minio-nfs
  resources:
    requests:
      storage: 1Mi # Size does not matter
