---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: osx
  namespace: dev
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: osx-secret
    creationPolicy: Owner
  data:
    - secretKey: vnc_password
      remoteRef:
        key: OSX__VNC_PASSWORD
