---
- hosts:
    # TODO
    # - master
    - worker
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 5 seconds...
      pause:
        seconds: 5
  tasks:
    - name: Ensure group "kah" exists with correct gid
      group:
        name: kah
        state: present
        gid: 568

    - name: Create kah user
      user:
        name: kah
        comment: k8s at home
        uid: 568
        group: kah

    - name: Ensure nfs and open-iscsi
      when: ansible_facts['distribution'] == 'Fedora'
      dnf:
        pkg:
          - iscsi-initiator-utils
          - nfs-utils

    - name: Ensure open-iscsi (Manjaro)
      when: ansible_facts['distribution'] == 'Archlinux' # Manjaro
      community.general.pacman:
        name:
          - open-iscsi

    - name: Setup storage disks (Fedora)
      when: ansible_facts['distribution'] == 'Fedora'
      block:
        - name: Create a new ext4 primary partition
          parted:
            device: /dev/nvme0n1
            number: 1
            state: present
            fs_type: ext4
        - name: Mount Disk to /data
          mount:
            path: /data
            src: /dev/nvme0n1
            fstype: ext4
            state: mounted
        - name: Give kah ownership
          file:
            path: /data
            owner: kah
            group: kah
            recurse: true
            # mode: '1777'

    - name: Setup storage disks (Manjaro)
      when: ansible_facts['distribution'] == 'Archlinux' # Manjaro
      block:
        - name: Create a new ext4 primary partition
          parted:
            device: /dev/sda
            number: 1
            state: present
            fs_type: ext4
        - name: Mount Disk to /data
          mount:
            path: /data
            src: /dev/sda1
            fstype: ext4
            state: mounted
        - name: Give kah ownership
          file:
            path: /data
            owner: kah
            group: kah
            recurse: true
            # mode: '1777'
