---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: ghcr.io/onedr0p/qbittorrent
      tag: 4.5.1@sha256:6e9433f545ae6b0a2b59a15ab24889031440fffc4515dfebb1829f2172fb9b00

    podAnnotations:
      setGateway: "true"

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups:
        - 65539

    initContainers:
      copy-config:
        image: busybox:latest@sha256:ef320ff10026a50cf5f0213d35537ce0041ac1d96e9b7800bafd8bc9eff6c693
        command:
          - "/bin/sh"
          - -c
        args:
          - cp /data/configfiles/* /data/config/
        volumeMounts:
          - name: config
            mountPath: /data/config
          - name: configfiles
            mountPath: /data/configfiles

    env:
      TZ: ${TIMEZONE}
      UMASK: "022"
      QBITTORRENT__PORT: &port 8080
      QBITTORRENT__BT_PORT: &port-bt "${VPN_FORWARDED_PORT_1}"
      QBITTORRENT__USE_PROFILE: "true"

    hostname: qbittorrent

    service:
      main:
        ports:
          http:
            port: *port
      bittorrent:
        enabled: true
        type: LoadBalancer
        ports:
          bittorrent:
            enabled: true
            port: *port-bt
            protocol: TCP
            targetPort: *port-bt

    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - host: &host "qbittorrent.${SECRET_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/config

      cache:
        enabled: true
        type: emptyDir
        mountPath: /config/qBittorrent/cache

      configfiles:
        enabled: true
        type: configMap
        name: qbittorrent-config
        mountPath: "-"

      data:
        enabled: true
        existingClaim: qbittorrent-config-v1
        mountPath: /config/qBittorrent/data

      media:
        enabled: true
        type: nfs
        server: '${NAS_ADDR}'
        path: /srv/nfs
        mountPath: /data/nas-media

    resources:
      requests:
        cpu: 35m
        memory: 765M
      limits:
        memory: 1426M
    # HACK
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
