---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: qbittorrent
      version: 13.5.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    initContainers:
      config-permission-fix:
        image: busybox
        command: ['/bin/chown', '-R', '568:568', '/config']
        volumeMounts:
          - name: config
            mountPath: /config
        securityContext:
          runAsGroup: 0
          runAsNonRoot: false
          runAsUser: 0

    image:
      repository: ghcr.io/k8s-at-home/qbittorrent
      tag: v4.4.2

    env:
      TZ: '${TIMEZONE}'

    podAnnotations:
      setGateway: 'true'

    settings:
      automaticPortSetup: false

    service:
      main:
        ports:
          http:
            port: 8080
      bittorrent:
        enabled: true
        type: LoadBalancer
        externalIPs:
          - '${SVC_QBITTORRENT_ADDRESS}'
        ports:
          bittorrent:
            enabled: true
            port: ${VPN_FORWARDED_PORT_1}
            protocol: UDP
            targetPort: ${VPN_FORWARDED_PORT_1}
        externalTrafficPolicy: Local

    ingress:
      main:
        enabled: true
        ingressClassName: 'nginx'
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
          hajimari.io/enable: 'true'
          hajimari.io/icon: 'cloud-download'
        hosts:
          - host: 'qb.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'qb.${SECRET_DOMAIN}'
            secretName: 'qbittorrent-tls'

    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch

    persistence:
      config:
        enabled: true
        existingClaim: qbittorrent-config-v2
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: '${NAS_ADDR}'
            path: /srv/nfs
        mountPath: /media

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 6000Mi
    # HACK
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
