---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: vpn-gateway-pod-gateway
  namespace: vpn
spec:
  egress:
    - ports:
        - port: 51820
          protocol: UDP
      to:
        - ipBlock:
            cidr: 0.0.0.0/0
    - to:
        - namespaceSelector: {}
  policyTypes:
    - Egress
