---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: miniflux-postgres
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: library/postgres
      tag: "10.10"
    env:
      - name: POSTGRES_USER
        value: miniflux
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: miniflux-secret
            key: POSTGRES_PASSWORD
      - name: POSTGRES_DB
        value: miniflux
      - name: PGDATA
        value: /var/lib/postgresql/data
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    service:
      main:
        enabled: true
        ports:
          http:
            enabled: true
            port: 5432
            protocol: TCP
    volumeClaimTemplates:
      - name: data
        mountPath: /var/lib/postgresql/data
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: longhorn
        subPath: miniflux_db
    podAnnotations:
      secret.reloader.stakater.com/reload: miniflux-secret
