# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: miniflux-secret
    namespace: media
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:tnTRJGVXJA==,iv:ROOApoSjEdgnDnt3UgKhXAQqRC2+ABoYWEIzOzoL7LQ=,tag:xZH/5g+ySdXVmxyFkiHZ8Q==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:SkOd6GUDw5TAp7xSZ3Ujgtfxj7pXe7zxjLEy8I4=,iv:ENxR0xAcEcSkP6ZHtqxS6fJSkcn+raxYh6QtyI/D/TQ=,tag:xjaJISCyQqyfp8Z70wdtBQ==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:IXPEm066JCr0j3lE7GNnxSpJwaECJKSr8knNqYY=,iv:Gz8AAL2a3NrzeNp6dPw0VDdOfajU1kW/ndoQww664j8=,tag:5IrytIov3lRPHOsNQysqHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZzhYS0lzejgwSDdYNW9p
            NGZhd2JCK0l1QU9rSWtGNTBZM2xKK0FhQTNNCnJZTXhaS2FiY0ZwU0RXYVlmM3JE
            NU4rdzBZbE1LL3l2UGVPMGl5bksrT1UKLS0tIFV6UEgrVDBZbXVQd3NCSUttb3JC
            WkFSdG04S29UTTRaazAzRU5pRU9PRzQK9mcUoHnapFuaAFHEz19/KdyX2zcZHm3Y
            XVvZfmLbRPBVn9MXIHyKia2aCXz4LsPp6l1KtcxUJDYNmkK/GBtKAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-30T18:41:41Z"
    mac: ENC[AES256_GCM,data:nAaEBDqlG0ct+xRX8RGEf+z0LcPtT4oZbloddqf9t8+bKExzVhERs9008lCXeg6a7xTtwGC6CMmCdsS4KX8uBubeLaxU81hL8ZUhXcDBwo981EgfIMiIU+ba+zeJSprqmLRYio28CAmqLV5tdPRfSc8uwQBeOpJ04B1m/Jo1Ffw=,iv:USSKUO42yEZKWnIXPgJkK44KvcV7nu/t6gqrD7h6jEA=,tag:OisjZYBACeIvdWtH58fJmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
