apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:+oN0URuCsOE=,iv:uG16/oiSgc4lNHuoyXaQIpY4aMyhW3qLWhvxjb2DFWU=,tag:ksmxf/9mwDfHaSl8xRiOYQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:GDz09AYN21BFbo3TaRW33eP2sMFXY4YTNA==,iv:h89CzzGAMK3dHuycb2pcpL8S9ZZ0QzJzM8VHH8ylnHo=,tag:EEvSs6wN6Ey3rM44pNV86A==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:x1A4Ror8duC5r/gET+c/PmN7dvT+JPg0Htt+oyUGTswbALhTnxM=,iv:CSv7qUb69WinyNS6fAgk48lZMIzoKwXxSqPwifXwKkE=,tag:mkPCI4s9TSKfJME9476p1Q==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:26lKtzKjL6uEjfPnCgGj4qFDG4fOPRCtLBfSm8w=,iv:5qrfB/o4Dwh2migJxJiFvZou9ceCnbn0GN/zkmrla8M=,tag:K0zjaNPKyw+dI5RveNYn4g==,type:str]
    B2_ACCOUNT_ID: ENC[AES256_GCM,data:vaWW3VunASyLzArXM5DcZzElJgkIZvZ5bA==,iv:Za/1y9wzAFpLGv9h2+L3hLdiHVnjsvWu6l+28hlinJ8=,tag:000c2K+q2LiHpTc7XO/QIw==,type:str]
    B2_ACCOUNT_KEY: ENC[AES256_GCM,data:RE2UHbk6I2mBL+o8SndZ+w8io65FYLNyDn8jJCNOew==,iv:jXlwGABTWfvry3q/73oT1mgem8eXqfp2V5nGPmrin0E=,tag:Im8eXS+jQjZMbkYPZw7ZhQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArVVZsQzNNZTJUOEkzemMw
            bHF3Q1ZnaU5pK3FJcnZsOVJEOTdGTDZuamc4ClJoQUZWVWpTaDVhSTlNWGFMVnUw
            Z1JXZDNMVHBZNXpTR0tmZ3BHR1pKRGsKLS0tIHlJeWRZSGlWcFg0YWR6aFVrenRR
            bUt4ZkYzbkxMSGt5VEZ4U0VlQXp6NkkKtIAe13jOmXPly5lNNhfO+HrWnmxpDjq1
            oiG1fizQsA0eBq3iIZsWDTLEAGMdWprG8YDrRR4KwTpfZuy+Pev7uA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-02T20:39:37Z"
    mac: ENC[AES256_GCM,data:rIUg5iKDRGm33RzNczZhuNeVX1qr+9YuEY5OytmjvXxU2pAYkoA6c/+hhJl4ZmGiBTWGes5FuMt7ziFNSBycIbSae49wjQkErgrxtqs/qQgCpCtJ+B/li53GFeTvouKzNWme2DpUviJUvDsP8AsuJASzuKzJOG1DsdQ0jlMKdXc=,iv:HYIUPICMNLJ7hoH+8BsatArT4S3qz425z9ve5PzMBMU=,tag:+3vCOZsof7Yhq6PmLbbJTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
