apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:31b4bP80Hwc=,iv:88K3nw2j4XcxS0Jpk9FWqHMhIaCAS+C+3+Lbeab7n20=,tag:hnbFle8DsnhXaFTd7E/NBQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ZSjMmBRA1kcgZBgedZ932h9vRWzhDo2Mjg==,iv:11J879O36VjCvRdH3Vzzirl9QhKm8hfBWqdl3kQ50g4=,tag:lAmdkZ1OqFM5G9oN55Sthw==,type:str]
    SECRET_RESTIC_REPOSITORY: ENC[AES256_GCM,data:49WYF+8F/bbIl/4=,iv:5i4wHw8rDScoy32dwWAQxe/7VqWcoH+XwFizdTQk2YY=,tag:Nsn+IAV29n/JY7YjbnaQgQ==,type:str]
    SECRET_RESTIC_PASSWORD: ENC[AES256_GCM,data:D/WvBPhdP0wnyNWDKiy5B1wDj1LfsbZDcbOpU2o=,iv:F9anACIfzG9xFDJXp0Nk9fkV5O3w1o/0fV8du6R70U4=,tag:MYspJGNVJr1+VFc++baMEQ==,type:str]
    SECRET_B2_ACCOUNT_ID: ENC[AES256_GCM,data:7x2SisKj0Y6PV3rKDX+laaAv8GiHYJaRyA==,iv:Mge8gm92Xd8IvjDGpaF4CWo0Av1hcwfcqQfylRYrsmY=,tag:SA9ARGX/U1GMWtx94woL2g==,type:str]
    SECRET_B2_ACCOUNT_KEY: ENC[AES256_GCM,data:j7OioPcNIFe1s4pRh5/Wk8MZ8XSXRj+fq2//FfS87Q==,iv:8oaBCS6O+B1VjfnWaJ00y7DsVD6CR8CmV0yl78K/DcQ=,tag:HbckAQR4h5Xy2b2EYfebSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1aryyzdumg5vg5pzy26vxffgjmckz3yqj33juffls3rhkcgeaxv5qumdcr3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M0Jmd1FvVFJzcno3a21D
            bkxxaS9Td3NtN2M4ZStVbjU3NFZUN0psTG5nClJ1ZkVKT1ZKWStabmhIZ2F4NGRG
            ajNSbXdWdGtiWGpSakpDRHN4SGJTYXcKLS0tIEZpR2NISkI0alNYNUt1MGprOUlS
            QnhmVlZFTm5RZnltcnVUSGg0a3dSRHcKJmnive3zBF7m+jmupP7DLumTZJx1dfZz
            ZNQpG61EgEqo+h894zMN5uyl/T29U0kEFh9bdZs7R3Q+qozLGq0CaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-02T22:19:56Z"
    mac: ENC[AES256_GCM,data:VlGHepDrv3GKpHup8aaPOKzFG33CJPqvosJV8dEBd/j0Kvv+u4fuiwY5c9qfstEZva9XOMaev7kltZ0GhdHNeftgVOERj5WIkX8v+2bxyzSWfvk2QhwIio0XcK32AdOqC137MNUmtewaogIX6hxegD9xF6WKFyzNE8sy3hPT8/M=,iv:ADHFKuoARF49IEiHK8NdDrXzWNb3nEiEXGGggkiwwb8=,tag:FkvpLcNqlPiXMtWdsjYGTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
