---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  KUBE_VIP_ADDR: "192.168.1.19"
  METALLB_LB_RANGE: "192.168.1.150-192.168.1.160"
  METALLB_K8S_GATEWAY_ADDR: "192.168.1.150"
  METALLB_INGRESS_ADDR: "192.168.1.151"
  #
  NAS_ADDR: '192.168.1.101'
  #
  SVC_HOME_ASSISTANT_ADDR: '192.168.1.152'
  SVC_MOSQUITTO_ADDR: '192.168.1.153'
  SVC_JELLYFIN_ADDR: '192.168.1.154'
  SVC_GROCY_ADDR: '192.168.1.155'
  SVC_BLOCKY_ADDR: '192.168.1.156'
  SVC_QBITTORRENT_ADDR: '192.168.1.157'
