---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: calibre-web
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    env:
      TZ: '${TIMEZONE}'
      PUID: 568
      PGID: 568

    ingress:
      main:
        enabled: true
        ingressClassName: 'nginx'
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
        hosts:
          - host: 'cw.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix

        tls:
          - hosts:
              - 'cw.${SECRET_DOMAIN}'
            secretName: 'calibre-web-tls'

    persistence:
      config:
        enabled: true
        existingClaim: calibre-web-config-v2
      music:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.1.101
            path: /srv/nfs/books
        mountPath: /books
