---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-web
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  dependsOn:
    - name: immich-server

  values:
    controller:
      replicas: 1
      strategy: RollingUpdate
      annotations:
        reloader.stakater.com/auto: "true"

    image:
      repository: ghcr.io/immich-app/immich-web
      tag: v1.53.0

    command: /bin/sh
    args:
      - ./entrypoint.sh

    env:
      DB_HOSTNAME:
        valueFrom:
          secretKeyRef:
            name: database-immich-user
            key: HOST
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: database-immich-user
            key: LOGIN
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: database-immich-user
            key: PASSWORD
      DB_DATABASE_NAME:
        valueFrom:
          secretKeyRef:
            name: database-immich-user
            key: DATABASE_NAME

    envFrom:
      - secretRef:
          name: immich-secret
      - configMapRef:
          name: immich-configmap

    service:
      main:
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/icon: simple-icons:jellyfin
        hosts:
          - host: &host "photos.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
              - path: /api
                pathType: Prefix
                service:
                  name: immich-server
                  port: 3001
        tls:
          - hosts:
              - *host

    persistence:
      library:
        enabled: true
        type: nfs
        server: '${NAS_ADDR}'
        path: /srv/nfs/photos/immich
        mountPath: /usr/src/app/upload

    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 500Mi
