---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: downloads
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: sonarr
      version: 16.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/sonarr
      tag: v3.0.7.1477
    env:
      TZ: '${TIMEZONE}'
    ingress:
      main:
        enabled: true
        ingressClassName: 'nginx'
        annotations:
          cert-manager.io/cluster-issuer: 'letsencrypt-production'
        hosts:
          - host: 'sonarr.${SECRET_DOMAIN}'
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - 'sonarr.${SECRET_DOMAIN}'
            secretName: 'sonarr-tls'
      api:
        enabled: true
        ingressClassName: "nginx"
        annotations:
        hosts:
          - host: "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /api
                pathType: Prefix
        tls:
          - hosts:
              - "sonarr.${SECRET_DOMAIN}"
            secretName: 'sonarr-tls'

    podSecurityContext:
      fsGroup: 0
      supplementalGroups:
        - 100

    persistence:
      config:
        enabled: true
        existingClaim: sonarr-config-v2
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: '${NAS_ADDR}'
            path: /srv/nfs
        mountPath: /media
      backup:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: '${NAS_ADDR}'
            path: /srv/nfs/backup/app/sonarr
        mountPath: /config/Backups
        readOnly: false

    resources:
      requests:
        memory: 250Mi
        cpu: 500m
      limits:
        memory: 1500Mi
