---
apiVersion: v1
kind: Secret
metadata:
  name: hass-restic-secret
type: Opaque
stringData:
  # The repository url
  RESTIC_REPOSITORY: "${SECRET_RESTIC_REPOSITORY}/hass"
  # The repository encryption key
  RESTIC_PASSWORD: "${SECRET_RESTIC_PASSWORD}"
  # ENV vars specific to the back end
  # https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html
  B2_ACCOUNT_ID: "${SECRET_B2_ACCOUNT_ID}"
  B2_ACCOUNT_KEY: "${SECRET_B2_ACCOUNT_KEY}"
---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: hass
  namespace: default
spec:
  sourcePVC: config-hass-0
  trigger:
    schedule: "0 0 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: hass-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 10
      within: 3d
