---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      type: statefulset

    image:
      repository: ghcr.io/bjw-s/calibre-web
      tag: 0.6.20@sha256:93766aed8f17d6006652fbcc3562d56d4b04de35e319283b22675f7653926504

    enableServiceLinks: false

    env:
      TZ: ${TIMEZONE}
      PUID: 568
      PGID: 568
      CACHE_DIR: /cache
    service:
      main:
        ports:
          http:
            port: 8083
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/icon: book-plus-multiple
        hosts:
          - host: &host "books.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [65539]
    volumeClaimTemplates:
      - name: config
        mountPath: /config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: ceph-block
    persistence:
      media:
        enabled: true
        type: nfs
        server: "${NAS_ADDR}"
        path: /srv/nfs/books/ebooks
        mountPath: /media
        readOnly: false
      cache:
        enabled: true
        type: emptyDir
        mountPath: /cache
    resources:
      requests:
        cpu: 15m
        memory: 273M
      limits:
        memory: 328M
