---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lidarr
  namespace: downloads
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: lidarr-secret
    creationPolicy: Owner
  data:
    - secretKey: LIDARR__API_KEY
      remoteRef:
        key: LIDARR__API_KEY
