---
# yaml-language-server: $schema=https://kubernetes-schemas.trux.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: miniflux-secret
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api
  target:
    name: miniflux-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        ADMIN_USERNAME: "{{ .ADMIN_USERNAME }}"
        ADMIN_PASSWORD: "{{ .ADMIN_PASSWORD }}"
        DATABASE_URL: "postgres://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres-rw.default.svc.cluster.local/miniflux?sslmode=disable"
        # Postgres Init
        INIT_POSTGRES_DBNAME: miniflux
        INIT_POSTGRES_HOST: postgres-rw.default.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .DB_USERNAME }}"
        INIT_POSTGRES_PASS: "{{ .DB_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  data:
    - secretKey: POSTGRES_SUPER_PASS
      remoteRef:
        key: POSTGRES_SUPER_PASS
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: MINIFLUX__ADMIN_USERNAME
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: MINIFLUX__ADMIN_PASSWORD
    - secretKey: DB_USER
      remoteRef:
        key: MINIFLUX__DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: MINIFLUX__DB_PASSWORD
