---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app miniflux
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: docker.io/miniflux/miniflux
      tag: latest
    env:
      TZ: "${TIMEZONE}"
      CREATE_ADMIN: "1"
      RUN_MIGRATIONS: "1"
      LOG_DATE_TIME: "1"
    envFrom:
      - secretRef:
          name: miniflux-secret
    service:
      main:
        ports:
          http:
            port: &port 8080
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: *port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          hajimari.io/enable: "true"
          hajimari.io/icon: rss
        hosts:
          - host: &host "rss.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    # resources:
    #   requests:
    #     cpu: 50m
    #     memory: 64Mi
    #   limits:
    #     memory: 96Mi
    podAnnotations:
      secret.reloader.stakater.com/reload: *app
